postgres:
  host: localhost
  port: 5432
  user: postgres
  password: password
  dbname: db
explorer:
  api_url: https://api.etherscan.io
  api_key: YOUR_API_KEY
node:
  url: YOUR_NODE_RPC
worker:
  id: 1
  interval: 3s
  max_concurrent: 100
wallets:
  - YOUR_WALLET_ADDRESS_1
  - YOUR_WALLET_ADDRESS_2